### ISSUE TITLE
I downloaded version 1.3 but window title says It's 1.2

### ISSUE THREAD

**Issue by nkrapivin** [soarqin/finalhe#11]
Downloaded Windows version.

**Comment by nekomania** [comment]
same here it says 1.2, and it still crash on downloading h-encore.zip
please fix.

**Comment by FilmgeekFR** [comment]
Hi ! Thanks a lot for this tool, but I've exactly the same pbm than nekomania :(

**Comment by caghandemir** [comment]
A workaround to the crash problem is to put "hencore.zip" in the "data" folder. It really should be there in the first place (since it's 700kB or something)

**Comment by soarqin** [comment]
I have released 1.4 which embedded h-encore.zip into binary, try download the win32 binary from releases tab and check if it works.

**Comment by nekomania** [comment]
Yes 1.4 worked perfectly, thank you very much :-D
