### ISSUE TITLE
Compiling finalhe on Linux openSUSE Leap 15.0

### ISSUE THREAD

**Issue by pseiler** [soarqin/finalhe#18]
Awesome work. Will try it as soon as I get finalhe compiled.
But I have one issue. Iconv isn't found on openSUSE, but there are headers from glibc-devel which should provide the file. Is this a cmake error (haven't encountered it in years) or is it from finalhe?
Every other dependency works fine (temporary commented this line
```#     find_package(Iconv REQUIRED)```

I think the following file from the package **glibc-devel** is relevant which isn't found by cmake.
```bash
rpm -ql glibc-devel | grep -i iconv
/usr/include/iconv.h
```

Do you have any hints how to fix the error?
I have

**Comment by pseiler** [comment]
Can be closed. My issue was, that I had an older cmake version (3.10). I used 3.12.0 to compile it, and it worked perfectly.

Here is a openSUSE package.
https://software.opensuse.org/package/finalhe

I add information about it via pull request to the README.md in your project

**Comment by soarqin** [comment]
it is strange that cmake 3.10 does not work with glibc iconv, I think it supported in a even slight older version, anywayz, I will fix this soon in cmake project

**Comment by pseiler** [comment]
The issue was that FindIconv.cmake wasn't in the package for cmake 3.10
Now it's located here:
/usr/share/cmake/Modules/FindIconv.cmake

The documenation lists the FindIconv page since cmake 3.11
https://cmake.org/cmake/help/v3.11/module/FindIconv.html

So I think 3.10 is simply too old to build the project.

**Comment by pseiler** [comment]
@soarqin now I get the error that some FindIconv dependencies missing.

Here is the error log:
<pre>
CMake Error at cmake/Modules/FindIconv.cmake:54 (include):
  include could not find load file:

    /home/abuild/rpmbuild/BUILD/finalhe-1.5.git.1533055119.bf4186b/cmake/Modules/CMakePushCheckState.cmake
Call Stack (most recent call first):
  CMakeLists.txt:38 (find_package)


CMake Error at cmake/Modules/FindIconv.cmake:56 (include):
  include could not find load file:

    /home/abuild/rpmbuild/BUILD/finalhe-1.5.git.1533055119.bf4186b/cmake/Modules/CheckCSourceCompiles.cmake
Call Stack (most recent call first):
  CMakeLists.txt:38 (find_package)


CMake Error at cmake/Modules/FindIconv.cmake:68 (cmake_push_check_state):
  Unknown CMake command "cmake_push_check_state".
Call Stack (most recent call first):
  CMakeLists.txt:38 (find_package)


-- Configuring incomplete, errors occurred!
</pre>

**Comment by soarqin** [comment]
fixed in latest commit, plz check if works

**Comment by pseiler** [comment]
works now. Thank you very much
