### ISSUE TITLE
Where to place language files when installed in system via package

### ISSUE THREAD

**Issue by pseiler** [soarqin/finalhe#25]
I installed the "FinalHE" binary to ```/usr/bin/FinalHE``` but I don't know where to place the language files in a typical linux QT environment.
I haven't found out the place with strace, because it only access/stat the \*.qm files, when they are present.

When placing the \*.qm language files in ```/usr/bin/language/*.qm``` it works.
But ```/usr/bin``` is not a place where to place non-binary files.
Is there place in ```/usr/share``` or something where these files are gonna read by FinalHE.

I only found files like these on my filesystem
```
/usr/share/qt5/translations/$PROGRAMNAME_$LANG_CODE.qm
```

This is my build instruction for rpm:
https://build.opensuse.org/package/view_file/home:seilerphilipp/finalhe/finalhe.spec?expand=1

**Comment by soarqin** [comment]
will fix it soon, put language files into individual app dir in ~/.config on POSIX systems (except mac).
