### ISSUE TITLE
A command-line version?

### ISSUE THREAD

**Issue by pthfdr-42** [soarqin/finalhe#35]
Like, a version that can directly run in a text terminal, without all those Qt bloats?

**Comment by KuromeSan** [comment]
theres still the http lib bloat that is cma.henkaku.xyz from molecule not wanting to share the keys for anything >_>

**Comment by soarqin** [comment]
@KuromeSan can use curl, Qt is not really needed for http request
@pthfdr-42 cli version is not hard to do actually, just replace Qt GUI codes with console codes. But I don't have time in short time, perhap do it while 3.69 being hacked.
