### ISSUE TITLE
h-encore can be trimmed to 7232KB.

### ISSUE THREAD

**Issue by KuromeSan** [soarqin/finalhe#37]
Only files acturally required for hencore to work:

	|   eboot.bin
	|   
	+---sce_module
	|       libc.suprx
	|       libfios2.suprx
	|       
	+---resource
	|   \---image
	|       \---sysc
	|               sysc_panel_button_base.png
	|               sysc_panel_button_mark.png
	|               
	+---sce_pfs
	|       files.db
	|       pflist
	|       unicv.db
	|       
	\---sce_sys
		|   clearsign
		|   keystone
		|   param.sfo
		|   
		\---package
				body.bin
				head.bin
				stat.bin
				tail.bin
				temp.bin
				
removing all other files results in 7232KB h-encore bubble. lol

**Comment by soarqin** [comment]
Thanks a lot, this is helpful, I will modify the trimming codes later.

**Comment by CelesteBlue-dev** [comment]
@soarqin any update on this ?

**Comment by soarqin** [comment]
implemented in v1.8, close
