### ISSUE TITLE
Crash when connect PsVita (MAC)

### ISSUE THREAD

**Issue by Reiza1993** [soarqin/finalhe#41]
The fist ti e works perfectly, but now is unusable, crash at lunch. 
![schermata 2019-01-20 alle 00 54 47](https://user-images.githubusercontent.com/40994896/51427610-01848680-1c4e-11e9-9dfd-3af727234850.png)
How can I fix It?

EDIT.SOLVED.

**Comment by soarqin** [comment]
This is eventually occured in my test, even on windows/linux, think it is a bug in libvitamtp or libusb.
