### ISSUE TITLE
Memecore not memcore

### ISSUE THREAD

**Issue by CelesteBlue-dev** [soarqin/finalhe#45]
Fix the typo please.

**Comment by CelesteBlue-dev** [comment]
and update Credits.

**Comment by soarqin** [comment]
my mistake. I have also replace release package with updated CREDITS.md

**Comment by CelesteBlue-dev** [comment]
Memecore not Memocore ! :cry:

**Comment by soarqin** [comment]
very sorry for the mistake, fixed again
