### ISSUE TITLE
Change firmware requirements. 

### ISSUE THREAD

**Issue by yatsukiko** [soarqin/finalhe#46]
The most useful reason for memecore to exist is to have it on 3.61, that way you can skip hassle updating to 3.65 and then downgrading to 3.60. Same goes for 3.63/3.67 as it's supported by h-encore. Though it should be mentioned that downgrade is recommended(if not necessary) when installing.

**Comment by soarqin** [comment]
okay, I will fix it and release 1.81 later

**Comment by StepS-** [comment]
3.63 support with h-encore is an undocumented possibility (because kernel nids match), needs to be tested if it still works with h-encore 2.0 (it did with 1.0).

**Comment by soarqin** [comment]
@StepS- already tested, confirmed not working

**Comment by StepS-** [comment]
Thanks!
