### ISSUE TITLE
Does not allow for updating from 3.67 to 3.68

### ISSUE THREAD

**Issue by BushMan01** [soarqin/finalhe#55]
My PSVita connected to the PC happily enough and transferred the h-encore package. It runs successfully on the device.
However, I am trying to update from v3.67 to v3.68. Any time I go to system update > Update from PC it says it is on latest firmware (this happens when I am not running h-encore app, as obviously the update option vanishes once you run it).
Please let me know if I am doing something wrong.
Sorry if this is a false problem, or if I have misread an instruction.

Gives me error code (C3-12049-6)

**Comment by soarqin** [comment]
1. Download 3.68 update and rename it to 368.PUP and put it in the FinelHE folder.
2. Disable version spoof on PSVita so that it can detect 3.68 update
3. Tick 3.68 update in FinalHE (click arrow on right edge to see function panel)

**Comment by BushMan01** [comment]
OK, it would be good if you could provide those instructions on readme
Also, I just updated to 3.70, used Trinity and then used modoru instead.
Thanks anyway.

**Comment by soarqin** [comment]
the update function intends to be used for vita which is not hacked.
if you have already intalled h-encore, just use reF00D plugin to play game without fw version limit, you do not have to update fw.
so I have not written instruction about that.

**Comment by BushMan01** [comment]
No, I was trying to do it on a regular Vita. Add an instruction regarding the "368.PUP" renaming. (I just had the file named as PSP2UPDAT.PUP)

I was still on a regular Vita and was trying to install version 3.68 to use H-encore to then downgrade to 3.60 for the permanent hack.

**Comment by soarqin** [comment]
rename is not actually needed. finalhe verifies pup size/sha1 to identify 3.60/3.65/3.68 update. you may used wrong pup. you can check it here: https://github.com/soarqinfinalhe/blob/master/src/vita.cc#L52

**Comment by BushMan01** [comment]
I must have used the wrong file. I don't have my computer with me right now, but I might be able to check the SHA256 hash when I get home.
