### ISSUE TITLE
Support h-encore² installation 

### ISSUE THREAD

**Issue by lordfriky** [soarqin/finalhe#57]

**Comment by StepS-** [comment]
h-encore² supports 3.65-3.71 (but we only need 3.69-3.71).

**Comment by StepS-** [comment]
It appears that 3.72 is also supported and uses the same payload. The initial reports of bittersmile being revoked on 3.72 turned out fake.
https://twitter.com/theflow0/status/1166456948876894209
We need 3.72 added in defines now.
