### ISSUE TITLE
I cant compile on Manjaro Linux

### ISSUE THREAD

**Issue by Pollito001** [soarqin/finalhe#7]
[ 86%] Building CXX object src/CMakeFiles/FinalHE.dir/finalhe.cc.o
/home/pollito/Desktop/finalhe-1.2/src/finalhe.cc: In constructor ‘FinalHE::FinalHE(QWidget*)’:
/home/pollito/Desktop/finalhe-1.2/src/finalhe.cc:15:37: error: expected ‘)’ before ‘FINALHE_VERSION_STR’
     setWindowTitle("Final h-encore " FINALHE_VERSION_STR);
                   ~                 ^~~~~~~~~~~~~~~~~~~~
                                     )
make[2]: *** [src/CMakeFiles/FinalHE.dir/build.make:125: src/CMakeFiles/FinalHE.dir/finalhe.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:367: src/CMakeFiles/FinalHE.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by 5H4D0WILA** [comment]
how do you go over compiling it?
I want to do it as well but i dont know how

**Comment by soarqin** [comment]
@Pollito001 It is my fault which made cmake broken at this point, try qmake (make a folder and run ```qmake -config release <finalhe root>``` and then ```make```)

**Comment by Pollito001** [comment]
@soarqin Thats works Thanks ;)
