### ISSUE TITLE
Cannot get past "Update System Software"

### ISSUE THREAD

**Issue by kupoback** [soarqin/finalhe#79]
I've tried all four methods to get my vita to connect, but the vita keeps sitting at "Update System Software." I am able to get Final h-encore to work, as it connects to the Vita, compiled, but beyond that I am unable to connect to my PC. I am on Windows 10, build 1909.

Methods tried:

- Reboot device
- Blocked Updated with DNS suggestion
- Enabled Flight Mode
- Installed QcmaDriver_winusb from version 1.91

**Comment by AaronVey22** [comment]
how did you fix it though????

i hate whenever peoplejust go "solved!" and don't explain how they solved it

**Comment by kupoback** [comment]
I didn't fix anything, I literally just didn't read the directions clearly. This was purely a user error.

**Comment by AaronVey22** [comment]
Oh. sorry

I ended fixing my issue (needing a system update) by... rebooting my vita.
