### ISSUE TITLE
Where is Linux?

### ISSUE THREAD

**Issue by 5H4D0WILA** [soarqin/finalhe#8]
The new release says that linux and mac os are now available.
But only mac was added

**Comment by soarqin** [comment]
Different linux distros get different way to install dependencies, so you have to compile it yourself.
For ubuntu: Install build-essential, libxml2-dev, libusb-dev, qt5-dev, zlib-dev and then follow the qmake way to build it

**Comment by 5H4D0WILA** [comment]
Ok thanks

**Comment by soarqin** [comment]
I have updated README to include build prerequisites instructions
