### ISSUE TITLE
Crashes when downloading h-encore.zip

### ISSUE THREAD

**Issue by noahc3** [soarqin/finalhe#9]
Every attempt to download h-encore.zip fails on Windows 10 Pro x64.
https://puu.sh/B3h7i/71369b3ebc.png

Visual Studio gives the following information:

Unhandled exception at 0x01198A54 in FinalHE.exe: 0xC0000094: Integer division by zero. occurred.

Edit: The program seems to successfully download and extract h-encore the first time (but still crashes afterwards). I think it might have to do with the progress bar having its max value set to 0, or something like that.

**Comment by soarqin** [comment]
This is caused by progress report with total set to 0 on url redirection, will fix it in no time
